name: linters

on:
  pull_request:
  push:

jobs:
  get-changed-files:
    runs-on: ubuntu-latest # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  kotlint-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Filter Kotlin files
        id: filter_kt_files
        run: |
          changed_files="${{ needs.get-changed-files.outputs.changed_files }}"
          kt_files=$(echo "$changed_files" | grep '\.kt$' || true)
          echo "::set-output name=kt_files::$kt_files"

      - name: Run Ktlint on changed Kotlin files
        if: ${{ steps.filter_kt_files.outputs.kt_files != '' }}
        uses: vroy/gha-kotlin-linter@v1
        with:
          files: ${{ steps.filter_kt_files.outputs.kt_files }}

  javascript-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Filter JavaScript files
        id: filter_js_files
        run: |
          changed_files="${{ needs.get-changed-files.outputs.changed_files }}"
          js_files=$(echo "$changed_files" | grep '\.js$' || true)
          echo "::set-output name=js_files::$js_files"

      - name: Run ESLint on changed JavaScript files
        if: ${{ steps.filter_js_files.outputs.js_files != '' }}
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: ${{ steps.filter_js_files.outputs.js_files }}

  python-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Filter Python files
        id: filter_py_files
        run: |
          changed_files="${{ needs.get-changed-files.outputs.changed_files }}"
          py_files=$(echo "$changed_files" | grep '\.py$' || true)
          echo "::set-output name=py_files::$py_files"

      - name: Run on Flake8 Lint changed Python files
        if: ${{ steps.filter_py_files.outputs.py_files != '' }}
        uses: py-actions/flake8@v2
        with:
          files: ${{ steps.filter_py_files.outputs.py_files }}

  sql-linter: #Check on dbt
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Filter SQL files
        id: filter_sql_files
        run: |
          changed_files="${{ needs.get-changed-files.outputs.changed_files }}"
          sql_files=$(echo "$changed_files" | grep '\.sql$' || true)
          echo "::set-output name=sql_files::$sql_files"

      - name: Run SQL Fluff on changed SQL files
        if: ${{ steps.filter_sql_files.outputs.sql_files != '' }}
        uses: yu-iskw/action-sqlfluff@v4
        with:
          reporter: github-pr-review
          sqlfluff_version: "3.0.7"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ steps.filter_sql_files.outputs.sql_files }}"

      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'

  yaml-yml-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Filter yml adm yaml files
        id: filter_yml_yaml_files
        run: |
          changed_files="${{ needs.get-changed-files.outputs.changed_files }}"
          yml_yaml_files=$(echo "$changed_files" | grep -E '\.yml$|\.yaml$' || true)
          echo "::set-output name=yml_yaml_files::$yml_yaml_files"

      - name: Run Yamllint on changed yaml and yml files
        if: ${{ steps.filter_yml_yaml_files.outputs.yml_yaml_files != '' }}
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ${{ steps.filter_yml_yaml_files.outputs.yml_yaml_files }}
          yamllint_strict: false
          yamllint_comment: true

  html-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          path: frontend
