name: linters

on:
  pull_request:
    branches:
      - main

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    name: Test changed-files
    permissions:
      pull-requests: read

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  kotlint-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Run Ktlint on changed Kotlin files
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          kt_files=$(echo "${ALL_CHANGED_FILES}" | grep '\.kt$' || true)
          if [ -n "$kt_files" ]; then
            echo "$kt_files" | xargs ktlint
          fi

  javascript-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Run ESLint on changed JavaScript files
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          js_files=$(echo "${ALL_CHANGED_FILES}" | grep '\.js$' || true)
          if [ -n "$js_files" ]; then
            echo "$js_files" | xargs eslint
          fi

  python-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run Flake8 on changed Python files
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          py_files=$(echo "${ALL_CHANGED_FILES}" | grep '\.py$' || true)
          if [ -n "$py_files" ]; then
            echo "$py_files" | xargs flake8
          fi

  sql-linter: #Check on dbt
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Run SQL Fluff on changed SQL files
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          sql_files=$(echo "${ALL_CHANGED_FILES}" | grep '\.sql$' || true)
          if [ -n "$sql_files" ]; then
            echo "$sql_files" | xargs sqlfluff lint --config .sqlfluff
          fi

  yaml-yml-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Run Yamllint on changed yaml and yml files
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          yml_yaml_files=$(echo "${ALL_CHANGED_FILES}" | grep -E '\.yml$|\.yaml$' || true)
          if [ -n "$yml_yaml_files" ]; then
            echo "$yml_yaml_files" | xargs yamllint -d "{extends: default, rules: {line-length: disable}}"
          fi

  html-linter:
    runs-on: ubuntu-latest
    needs: get-changed-files
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Run htmltest
        if: ${{ env.ALL_CHANGED_FILES && env.ALL_CHANGED_FILES != '' }}
        run: |
          html_files=$(echo "${ALL_CHANGED_FILES}" | grep '\.html$' || true)
          if [ -n "$html_files" ]; then
            echo "$html_files" | xargs htmltest
          fi
